boralanchar_heroku/urls.py
# coding: utf-8

from users.views import UserDashboardView
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^estabelecimento/', include('estabelecimento.urls', namespace='estabelecimento')),
                       url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
                       url(r'^location/', include('location.urls', namespace='location')),

                       # User dashboard
                       url(r'^user/dashboard/$', UserDashboardView.as_view(), name='user_dashboard'),

                       # Accounts
                       url(r'^accounts/', include('accounts.urls')),

                       # Cart
                       url(r'^cart/', include('cart.urls', namespace='cart')),

                       url(r'^', include('website.urls', namespace='website'))) + static(settings.MEDIA_URL,
                                                                                              document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('cart.views',
    url(r'^$', 'get_cart', name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'add_to_cart', name='add'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/new/$', 'add_to_cart',
        kwargs={'ensure_new': True}, name='add_new'),
    url(r'^decrement/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'decrement_quantity', name='decrement'),
    url(r'^decrement/item/(?P<item_id>\d+)/(?P<quantity>\d+)/$',
        'decrement_item_quantity', name='decrement_item'),
    url(r'^remove/(?P<product_id>\d+)/$', 'remove_from_cart', name='remove'),
)

estabelecimento/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('estabelecimento.views',
                       url(r'^$', 'estabelecimentos', name='estabelecimentos'),
                       url(r'^(?P<pk>\d+)/$', 'estabelecimento_detail', name='estabelecimento_detail'))

location/urls.py
# coding: utf-8
from mixin import HybridDetailView
from models import Uf, Cidade, Bairro
from django.conf.urls import patterns, url
from views import GMapsTemplateView

urlpatterns = patterns('location.views',
    url(r'^set/', 'set', name='set'),
    url(r'^get/', 'get', name='get'),
    url(r'^clear/', 'clear', name='clear'),
    url(r'^cadastrar-endereco/$', GMapsTemplateView.as_view(), name='cadastrar-endereco'),
    
    (r'^uf/(?P<pk>\d)$', HybridDetailView.as_view(model=Uf)),
    (r'^cidade/(?P<pk>\d)$', HybridDetailView.as_view(model=Cidade)),
    (r'^bairro/(?P<pk>\d)$', HybridDetailView.as_view(model=Bairro)),
)

website/urls.py
# coding: utf-8
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('website.views',
    url(r'^$', 'index', name='index'),
    url(r'^como-funciona/$', 'como_funciona', name='como_funciona'),
    url(r'^contato/$', 'contato', name='contato'),

    url(r'^meus-pedidos/$', 'meus_pedidos', name='meus_pedidos'),
    url(r'^cadastre-se/$', 'cadastre_se', name='cadastre_se'),
    url(r'^login/$', 'login', name='login'),
    url(r'^indicar-estabelecimento/$', 'indicar_estabelecimento', name='indicar_estabelecimento'),

    url(r'^como-acompanhar-meu-pedido/$', 'como_acompanhar_meu_pedido', name='como_acompanhar_meu_pedido'),
    url(r'^perguntas-frequentes/$', 'perguntas_frequentes', name='perguntas_frequentes'),
    url(r'^termos-de-uso/$', 'termos_de_uso', name='termos_de_uso'),
    url(r'^empresa/$', 'empresa', name='empresa'),

    url(r'^vantagens-estabelecimento/$', 'vantagens_estabelecimento', name='vantagens_estabelecimento'),
    url(r'^area-estabelecimento/$', 'area_estabelecimento', name='area_estabelecimento'),
)

estabelecimento/models.py
# -*- coding:utf-8 -*-
from location.models import Uf, Cidade, Bairro
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from datetime import datetime

STATUS_ESTABELECIMENTO_FECHADO = '0'
STATUS_ESTABELECIMENTO_ABERTO = '1'
STATUS_ESTABELECIMENTO_CHOICES = (
    (STATUS_ESTABELECIMENTO_FECHADO, _('Fechado')),
    (STATUS_ESTABELECIMENTO_ABERTO, _('Aberto')),
)


class Permissao(models.Model):
    nome = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name = 'permissão'
        verbose_name_plural = 'permissões'

    def __unicode__(self):
        return self.nome


class Papel(models.Model):
    titulo = models.CharField('Título', max_length=50)
    descricao = models.TextField('Descrição', blank=True, null=True)
    permissoes = models.ManyToManyField(Permissao, related_name='papeis', verbose_name='Permissões', blank=True)

    class Meta:
        verbose_name = 'papel'
        verbose_name_plural = 'papeis'

    def __unicode__(self):
        return self.titulo


class Colaborador(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    estabelecimento = models.ForeignKey('Estabelecimento')
    papel = models.ForeignKey(Papel, related_name='colaboradores')

    class Meta:
        verbose_name = 'Colaborador'
        verbose_name_plural = 'Colaboradores'


class Visualizacao(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True)
    estabelecimento = models.ForeignKey('Estabelecimento', related_name='visualizacoes')
    ip_address = models.IPAddressField()

    class Meta:
        verbose_name = 'Visualização'
        verbose_name_plural = 'Visualizações'


class Estabelecimento(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES, blank=True)
    ativo = models.BooleanField(default=True)
    status = models.CharField(max_length=1, default=STATUS_ESTABELECIMENTO_FECHADO,
                              choices=STATUS_ESTABELECIMENTO_CHOICES)
    dataCadastro = models.DateTimeField(default=datetime.now(), verbose_name='Data de Cadastro')

    uf = models.ForeignKey(Uf)
    cidade = models.ForeignKey(Cidade)
    bairro = models.ForeignKey(Bairro)
    endereco = models.CharField(max_length=255, verbose_name='Endereço')
    numero = models.CharField(max_length=30, verbose_name='Número', blank=True)

    '''
    complemento = models.CharField(max_length=30, verbose_name='Complemento', blank=True)
    cep = models.CharField(max_length=8, verbose_name='CEP', blank=True)
    
    razao_social = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    email = models.EmailField('Email', blank = True, null = True, max_length = 255)
    cnpj = models.CharField(max_length=14, blank=True, verbose_name='CNPJ')
    
    telefone = models.CharField(max_length=11, blank=True, verbose_name='Telefone')
    celular = models.CharField(max_length=11, blank=True, verbose_name='Celular')
    
    site = models.CharField(max_length=255, blank=True)
    '''

    # membros com acesso parcial/total ao dashboard do estabelecimento
    colaboradores = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='estabelecimentos',
                                           through=Colaborador)

    meios_pagamentos = models.ManyToManyField('MeioPagamento', verbose_name='Meios de pagamento')
    tipos_cozinha = models.ManyToManyField('TipoCozinha', verbose_name='Tipos de cozinha')

    horario_funcionamento_domingo = models.CharField(max_length=20, verbose_name='Hor. Domingo')
    horario_funcionamento_segunda = models.CharField(max_length=20, verbose_name='Hor. Segunda')
    horario_funcionamento_terca = models.CharField(max_length=20, verbose_name='Hor. Terça')
    horario_funcionamento_quarta = models.CharField(max_length=20, verbose_name='Hor. Quarta')
    horario_funcionamento_quinta = models.CharField(max_length=20, verbose_name='Hor. Quinta')
    horario_funcionamento_sexta = models.CharField(max_length=20, verbose_name='Hor. Sexta')
    horario_funcionamento_sabado = models.CharField(max_length=20, verbose_name='Hor. Sábado')

    class Meta:
        ordering = ['nome']
        verbose_name = u'Estabelecimento'
        verbose_name_plural = u'Estabelecimentos'

    def __unicode__(self):
        return self.nome

    def save(self, *args, **kwargs):
        unicode(self.imagem.name)
        super(Estabelecimento, self).save(*args, **kwargs)

    def horario_funcionamento_hoje(self):
        return {
            0: self.horario_funcionamento_segunda,
            1: self.horario_funcionamento_terca,
            2: self.horario_funcionamento_quarta,
            3: self.horario_funcionamento_quinta,
            4: self.horario_funcionamento_sexta,
            5: self.horario_funcionamento_sabado,
            6: self.horario_funcionamento_domingo,
        }.get(datetime.today().weekday()) or None

    def funcionando(self):
        return self.status == STATUS_ESTABELECIMENTO_ABERTO

    #        hora = self.horario_funcionamento_hoje()
    #        m = re.search('(\d{1,2}:\d\d).+(\d{1,2}:\d\d)', hora)
    #
    #        try:
    #            if len(m.groups()) == 2:
    #                inicio = m.group(0)
    #                termino = m.group(1)
    #        except:
    #            pass
    #        # todo fix it
    #        return True

    def locais_entrega(self):
        return self.localentrega_set.all()

    def lst_meios_pagamentos(self):
        return self.meios_pagamentos.all()

    def lst_tipos_cozinha(self):
        return self.tipos_cozinha.all()


class LocalEntrega(models.Model):
    taxa_entrega = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Taxa de entrega')
    tempo_aproximado = models.CharField(max_length=20, verbose_name='Tempo aproximando')
    estabelecimento = models.ForeignKey(Estabelecimento)
    bairro = models.ForeignKey(Bairro)

    class Meta:
        verbose_name = u'Local de Entrega'
        verbose_name_plural = u'Locais de Entrega'

    def taxa_entrega_formatada(self):
        return ('%10.2f' % self.taxa_entrega).strip().replace('.', ',')


class TipoCozinha(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES, blank=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']
        verbose_name = u'Tipo de cozinha'
        verbose_name_plural = u'Tipos de cozinha'

    def save(self, *args, **kwargs):
        unicode(self.imagem.name)
        super(TipoCozinha, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.nome


class MeioPagamento(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES)
    ativo = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']
        verbose_name = u'Meio de pagamento'
        verbose_name_plural = u'Meios de pagamento'

    def save(self, *args, **kwargs):
        unicode(self.imagem.name)
        super(MeioPagamento, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.nome


class CategoriaProduto(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES, blank=True)
    ativo = models.BooleanField(default=True)

    class Meta:
        ordering = ['nome']
        verbose_name = u'Categoria de produto'
        verbose_name_plural = u'Categorias de produto'

    def save(self, *args, **kwargs):
        unicode(self.imagem.name)
        super(CategoriaProduto, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES, blank=True)
    ativo = models.BooleanField(default=True)
    preco = models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')
    somente_adicional = models.BooleanField(verbose_name='Este Produto é somente adicional?')
    nao_pode_ser_adicional = models.BooleanField(verbose_name='Este produto não deve ser um adicional?')
    estabelecimento = models.ForeignKey(Estabelecimento)
    categoria_produto = models.ForeignKey(CategoriaProduto, verbose_name='Categoria do produto')

    etapas_adicionais = models.ManyToOneRel('EtapaAdicional', field_name='etapas_adicionais')

    class Meta:
        ordering = ['nome']
        verbose_name = u'Produto'
        verbose_name_plural = u'Produtos'

    def __unicode__(self):
        return self.nome

    def save(self, *args, **kwargs):
        unicode(self.imagem.name)
        super(Produto, self).save(*args, **kwargs)

    def preco_formatado(self):
        return ('%10.2f' % self.preco).strip().replace('.', ',')


class EtapaAdicional(models.Model):
    nome = models.CharField(max_length=50, blank=False)
    descricao = models.CharField(max_length=255, blank=True, verbose_name='Descrição')
    imagem = models.ImageField(upload_to=settings.UPLOAD_TO_IMAGES, blank=True)
    ativo = models.BooleanField(default=True)
    ordem_exibicao = models.IntegerField(verbose_name='Ordem de exibição')
    quantidade_adicionais_simultaneos = models.IntegerField(
        verbose_name='Quantidade de adicionais que podem ser selecionados simultaneamente')

estabelecimento/templates/estabelecimento_detail.html
{% extends "base.html" %}
{% load cart %}

{% block script %}
    <script src="{{ STATIC_URL }}js/jquery.cookie.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/noty/jquery.noty.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/noty/layouts/top.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/noty/themes/default.js" type="text/javascript"></script>

    <script type="text/javascript">
    function on_minus_click_event(e){
        e.preventDefault();
        var url = $(this).attr('href');

        $.ajax(url, {
            type: 'post',
            data: { csrfmiddlewaretoken: $.cookie('csrftoken') },
            success: function(data, xhr, textstatus){
                update_cart(data);
            },
            complete: function(xhr, textstatus){}
        });
    };

    function update_cart(data){
        var items = data['items'];
        var formatted_total_value = data['formatted_total_value'];
        var formatted_summary = data['formatted_summary'];
        var formatted_delivery_tax = data['formatted_delivery_tax'];
        var tbody_element = $('<tbody></tbody>');

        for(i in items){
            var item = items[i];
            var id_item = item['id_item'];
            var quantidade = item['quantidade'];
            var nome_produto = item['nome_produto'];
            var preco_unidade = item['preco_unidade'];
            var preco_total = item['preco_total'];
            var observacao = item['observacao'];

            var minus_url = '{% url 'cart:decrement_item' 0 1 %}'
                    .replace('0', id_item);
            var minus_td_element = $('<td style="white-space: nowrap"></td>');
            var minus_link = $('<a class="minus">[-]</a>');
            minus_link.attr('href', minus_url);
            minus_link.click(on_minus_click_event);
            minus_td_element.append(minus_link);

            var tr_element = $('<tr></tr>');
            tr_element.append('<td>'+ quantidade +'</td>');
            tr_element.append('<td>'+ nome_produto +'</td>');
            tr_element.append('<td style="white-space: nowrap">R$ '+ preco_total +'</td>');
            tr_element.append('<td>' + observacao + '</td>');
            tr_element.append(minus_td_element);

            tbody_element.append(tr_element);
        }

        var taxes = '<tr>' +
                '<td colspan="2">Taxa de entrega</td>' +
                '<td colspan="3" style="white-space: nowrap">R$ '+ formatted_delivery_tax +'</td>' +
                '</tr>';
        tbody_element.append(taxes);

        var bottom_html = '<tr>' +
                '<td colspan="2">Total</td>' +
                '<td colspan="3" style="font-weight: bold; font-size: 16px; color: #880d16; white-space: nowrap" colspan="2">R$ '+
                formatted_total_value +'</td>' +
                '</tr>';
        tbody_element.append(bottom_html);
        $('#enduser_cart').find('tbody').replaceWith(tbody_element);
    };

    $(document).ready(function(){
        $('#enduser_cart tr a.minus').click(on_minus_click_event);

        $('.item_produto button').click(function(){
            var parent = $(this).parent();
            var id_produto = parent.find('input[name=id_produto]').val();
            var qty = parent.find('input[name=qty]').val();
            var obs = parent.find('textarea[name=observation]').val();
            var url = '{% url 'cart:add_new' 0 0 %}';

            // clear field values
            parent.find('textarea[name=observation]').val('');
            parent.find('input[name=qty]').val(1);

            $.ajax(url.replace('0', id_produto).replace('0', qty), {
                type:'post',
                data: {
                    csrfmiddlewaretoken: $.cookie('csrftoken'),
                    observation: obs
                },
                success: function(data, xhr, textstatus){
                    update_cart(data);
                },
                complete: function(xhr, textstatus){}
            });
        });
    });
    </script>
{% endblock %}

{% block content %}
    <div class="row">
        <aside class="span3">
            {% include "filtros_produto.html" %}
        </aside>

        <div class="span6">
            <h1>{{ estabelecimento.nome }}</h1>
            <h3><small>{{estabelecimento.descricao}}</small></h3>
            <h3>
                {% for tipo_cozinha in estabelecimento.lst_tipos_cozinha %}
                    {{ tipo_cozinha.nome }}{% if not forloop.last %},{% endif %}
                {% endfor %}
            </h3>
            <div>
                <p>
                    {{ estabelecimento.endereco }}, {{ estabelecimento.numero }} - {{ estabelecimento.bairro.descricao }}<br />
                    {% for meio_pagamento in estabelecimento.lst_meios_pagamentos %}
                        {% if meio_pagamento.imagem %}
                            <img src="{{meio_pagamento.imagem.url}}"  alt="{{meio_pagamento.nome}}" title="{{meio_pagamento.descricao}}" width="16" height="16" />
                        {% else %}
                            {{ meio_pagamento.nome }},
                        {% endif %}
                    {% endfor %}
                </p>
                
                <div class="btn-group pull-left">
			        <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">
                        {% for local_entrega in estabelecimento.locais_entrega %}
                            {% if endereco %}
                                {% if local_entrega.bairro.pk == endereco.bairro.pk %}
                                    <i class="icon-map-marker"></i> {{ local_entrega.bairro.descricao }}
                                    <i class="icon-time"></i> {{ local_entrega.tempo_aproximado }} min
                                    <strong>R$</strong> {{ local_entrega.taxa_entrega_formatada }}
                                {% endif %}
                            {% endif %}
                        {% endfor %}
                        <span class="caret"></span></button>
			        <ul class="dropdown-menu">
			            <li>
			                <p><strong>&nbsp;Área de Cobertura:</strong></p>
			                <table class="drop-hours">
		                        {% for local_entrega in estabelecimento.locais_entrega.all %}
		                            <tr>
		                                <td title="Bairro"><i class="icon-map-marker"></i> {{ local_entrega.bairro.descricao }}</td>
		                                <td title="Tempo Aproximado de Entrega"><i class="icon-time"></i> {{ local_entrega.tempo_aproximado }} min</td>
		                                <td title="Taxa de Entrega"><strong>R$</strong> {{ local_entrega.taxa_entrega_formatada }}</td>
		                            </tr>
		                        {% endfor %}
		                    </table>
			            </li>
			        </ul>
			    </div>&nbsp;

                <div class="btn-group pull-left">
                    <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown"><i class="icon-time"></i> {{ estabelecimento.horario_funcionamento_hoje }} <span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li>
                        	<p><strong>&nbsp;Horário Funcionamento:</strong></p>
                            <table class="drop-hours">
                                <tr><td>DOMINGO</td><td>{{ estabelecimento.horario_funcionamento_domingo }}</td></tr>
                                <tr><td>SEGUNDA</td><td>{{ estabelecimento.horario_funcionamento_segunda}}</td></tr>
                                <tr><td>TERÇA</td><td>{{ estabelecimento.horario_funcionamento_terca }}</td></tr>
                                <tr><td>QUARTA</td><td>{{ estabelecimento.horario_funcionamento_quarta }}</td></tr>
                                <tr><td>QUINTA</td><td>{{ estabelecimento.horario_funcionamento_quinta }}</td></tr>
                                <tr><td>SEXTA</td><td>{{ estabelecimento.horario_funcionamento_sexta }}</td></tr>
                                <tr><td>SÁBADO</td><td>{{ estabelecimento.horario_funcionamento_sabado }}</td></tr>
                            </table>
                        </li>
                    </ul>
                </div>

                {% if estabelecimento.status == '0' %}
                    <span class="badge badge-important pull-right" style="padding: 5px 10px">Fechado</span>
                {% else %}
                    <span class="badge badge-success pull-right" style="padding: 5px 10px">Aberto</span>
                {% endif %}

            </div>
            <hr />
            <div class="alert">                
                {% if paginator.count != 0 %}
                	<h3>{{ paginator.count }} produto{{ paginator.object_list|pluralize }} encontrado{{ paginator.object_list|pluralize }}!</h3>
                {% else %}
                	<h3>Sinto muito, o estabelecimento ainda não cadastrou seus produtos.</h3>
               	{% endif %}
            </div>
            {% include "resultados_produtos.html" %}
        </div>

        <!--div class="span2" style="position: fixed; top: 60px; right: 50px;"-->
        <div id="cart" class="span3">
            <div class="thumbnail">
                {% if estabelecimento.imagem %}
                    <img class="imagem_estabelecimento" src="{{ estabelecimento.imagem.url }}"
                         alt="{{ estabelecimento.nome }}" title="{{ estabelecimento.descricao }}" width="270" height="120" />
                {% else %}
                    <img src="{{ STATIC_URL }}img/estabelecimento.png" alt="{{estabelecimento.nome}}" title="{{estabelecimento.descricao}}" width="270" height="120" />
                {% endif %}
            </div><br />
            <h4 style="margin-bottom: 8px; margin-left: 10px; white-space: nowrap;"><i style="margin-top: 1px;" class="icon-shopping-cart"></i>&nbsp;Meu Pedido</h4>
            <div class="thumbnail side-filter" style="background-color: #FFF3E5;">
                <table id="enduser_cart" class="table" style="margin-bottom: 0;">
                    <thead>
                        <tr>
                            <th style="border: none;">Qtd</th>
                            <th style="border: none;">Ítem</th>
                            <th style="border: none;">Valor</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart %}
                            <tr>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.product }}</td>
                                <td style="white-space: nowrap">R$ {{ item.total_price|format_money }}</td>
                                <td>{{ item.observation }}</td>
                                <td style="white-space: nowrap"><a href="{% url 'cart:decrement_item' item.id 1 %}" class='minus'>[-]</a></td>
                            </tr>

                            {% if forloop.last %}
                            <tr>
                                <td colspan="2">Taxa de entrega</td>
                                <td colspan="3" style="white-space: nowrap">R$ {{ taxa_de_entrega|format_money }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">Total</td>
                                <td style="font-weight: bold; font-size: 16px; color: #880d16;" colspan="3">R$ {{ valor_total|format_money }}</td>
                            </tr>
                            {% endif %}
                        {% empty %}
                            <tr>
                                <td colspan="2">Taxa entrega</td>
                                <td colspan="3" style="white-space: nowrap">R$ {{ taxa_de_entrega|format_money }}</td>
                            </tr>
                            <tr>
                                <td colspan="2">Total</td>
                                <td style="font-weight: bold; font-size: 16px; color: #880d16; white-space: nowrap" colspan="3">R$ {{ taxa_de_entrega|format_money }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div style="padding: 8px; text-align: center; border-top: solid 1px #ddd">
                    <a class="btn btn-danger" href="{% url 'cart:get' %}">Fechar pedido</a>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

estabelecimento/templates/filtros_produto.html
<div class="well side-filter">
    {% include "form_local_leitura.html" %}
    {% include "form_alterar_localidade.html" %}

	{% if categorias_produtos %}
	    <div class="well well-small">
	        <ul class="nav nav-list">
	            <li class="nav-header">
	                <h4>Navegue aqui</h4>
	            </li>
	            <li class="divider"></li>
	        </ul>
	        <ul class="nav nav-list">
	        {% load filtertag %}
	        {% load evaltag %}
	        {% load truncateletterstag %}
	        
	        {% for categoria_produto in categorias_produtos %}
		        {% if categoria_produto.produto_set.count and forloop.first %}
					<li class="nav-header">Categoria de Produtos</li>
		        {% endif %}
		
		        {% eval produtos_estabelecimento.filter(categoria_produto=categoria_produto).distinct().count() as total %}
            	{% if total > 0 %}
	            <li class="filters">
    	        	<span class="{% filter_mark categoria_produto '' icon-ok %}"></span>

		            <label for="categoria_{{ forloop.counter }}">
		            	<a title="{{ categoria_produto.descricao }}" href="{% filter_url categoria_produto %}">{{ categoria_produto.nome|truncateletters:14 }}</a>
	    					<span class="badge">{{ total }}</span>
					</label>
            	</li>
            	{% endif %}
	        {% endfor %}
	        </ul>
	    </div>
    {% endif %}
</div>

estabelecimento/templates/paginacao.html
{% if page.has_other_pages %}
<div class="btn-toolbar">
    <div class="btn-group">
    	{% if page.has_previous %}
			<a href="?p={{ page.previous_page_number }}" class="btn"><i class="icon-arrow-left"></i></a>
        {% else %}
        	<span class="btn disabled"><i class="icon-arrow-left"></i></span>
        {% endif %}
    
    	{% for page_number in paginator.page_range %}
	        {% if page.number == page_number %}
	        	<span class="btn disabled">{{ page_number }}</span>
	        {% else %}
	        	<a href="?p={{ page_number }}" class="btn">{{ page_number }}</a>
	        {% endif %}
	    {% endfor %}
        
        {% if page.has_next %}
        	<a href="?p={{ page.next_page_number }}" class="btn"><i class="icon-arrow-right"></i></a>
        {% else %}
        	<span class="btn disabled"><i class="icon-arrow-right"></i></span>
        {% endif %}
    </div>
</div>
{% endif %}