boralanchar_heroku/urls.py
# coding: utf-8

from users.views import UserDashboardView
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^estabelecimento/', include('estabelecimento.urls', namespace='estabelecimento')),
                       url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
                       url(r'^location/', include('location.urls', namespace='location')),

                       # User dashboard
                       url(r'^user/dashboard/$', UserDashboardView.as_view(), name='user_dashboard'),

                       # Accounts
                       url(r'^accounts/', include('accounts.urls')),

                       # Cart
                       url(r'^cart/', include('cart.urls', namespace='cart')),

                       url(r'^', include('website.urls', namespace='website'))) + static(settings.MEDIA_URL,
                                                                                              document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('cart.views',
    url(r'^$', 'get_cart', name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'add_to_cart', name='add'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/new/$', 'add_to_cart',
        kwargs={'ensure_new': True}, name='add_new'),
    url(r'^decrement/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'decrement_quantity', name='decrement'),
    url(r'^decrement/item/(?P<item_id>\d+)/(?P<quantity>\d+)/$',
        'decrement_item_quantity', name='decrement_item'),
    url(r'^remove/(?P<product_id>\d+)/$', 'remove_from_cart', name='remove'),
)

dashboard/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('dashboard.views',
    url(r'^(?P<id_estabelecimento>\d+)/toggle/$',
        'toggle_estabelecimento', name='toggle_estabelecimento'),

    url(r'^(?P<id_estabelecimento>\d+)/pedidos/$',
        'pedidos_view', name='pedidos'),

    url(r'^(?P<id_estabelecimento>\d+)/pedido/(?P<id_pedido>\d+)/$',
        'pedido_detail', name='pedido'),

    url(r'^(?P<id_estabelecimento>\d+)/pedido/(?P<id_pedido>\d+)/edit/status/$',
        'muda_status_pedido', name='muda_status_pedido'),

    url(r'^(?P<id_estabelecimento>\d+)/produtos/$',
        'produtos_view', name='produtos'),

    url(r'^(?P<id_estabelecimento>\d+)/produto/(?P<id_produto>\d+)/toggle/$',
        'produto_toggle_disponibilidade', name='produto_toggle_disponibilidade'),
)

location/urls.py
# coding: utf-8
from mixin import HybridDetailView
from models import Uf, Cidade, Bairro
from django.conf.urls import patterns, url
from views import GMapsTemplateView

urlpatterns = patterns('location.views',
    url(r'^set/', 'set', name='set'),
    url(r'^get/', 'get', name='get'),
    url(r'^clear/', 'clear', name='clear'),
    url(r'^cadastrar-endereco/$', GMapsTemplateView.as_view(), name='cadastrar-endereco'),
    
    (r'^uf/(?P<pk>\d)$', HybridDetailView.as_view(model=Uf)),
    (r'^cidade/(?P<pk>\d)$', HybridDetailView.as_view(model=Cidade)),
    (r'^bairro/(?P<pk>\d)$', HybridDetailView.as_view(model=Bairro)),
)

website/urls.py
# coding: utf-8
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('website.views',
    url(r'^$', 'index', name='index'),
    url(r'^como-funciona/$', 'como_funciona', name='como_funciona'),
    url(r'^contato/$', 'contato', name='contato'),

    url(r'^meus-pedidos/$', 'meus_pedidos', name='meus_pedidos'),
    url(r'^cadastre-se/$', 'cadastre_se', name='cadastre_se'),
    url(r'^login/$', 'login', name='login'),
    url(r'^indicar-estabelecimento/$', 'indicar_estabelecimento', name='indicar_estabelecimento'),

    url(r'^como-acompanhar-meu-pedido/$', 'como_acompanhar_meu_pedido', name='como_acompanhar_meu_pedido'),
    url(r'^perguntas-frequentes/$', 'perguntas_frequentes', name='perguntas_frequentes'),
    url(r'^termos-de-uso/$', 'termos_de_uso', name='termos_de_uso'),
    url(r'^empresa/$', 'empresa', name='empresa'),

    url(r'^vantagens-estabelecimento/$', 'vantagens_estabelecimento', name='vantagens_estabelecimento'),
    url(r'^area-estabelecimento/$', 'area_estabelecimento', name='area_estabelecimento'),
)

boralanchar_heroku/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta name="description" content="boralanchar.com.br :: Peça seu lanche!" />
	<meta http-equiv="copyright" content="boralanchar.com.br" /> 
	<meta name="google-site-verification" content="RRLh8iB7DFPlnFTY64M1A1KxsZ6i289N8gHqgRz1ADE" />
	<meta name="keywords" content="" />

	<meta http-equiv="pragma" content="no-cache" />
	<meta http-equiv="cache-control" content="no-cache, no-store" />
	<meta http-equiv="expires" content="Mon, 06 Jan 1990 00:00:01 GMT" />

	<meta name="robots" content="index, follow" />
	<meta name="googlebot" content="index, follow">
	
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta http-equiv="x-ua-compatible" content="IE=EmulateIE7" />
	<meta http-equiv="content-language" content="pt-br" />
    
	{% block style %}
        <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" rel="stylesheet">
        <style>
            @media (min-width: 768px) and (max-width: 979px) {
                #wrap > .container { padding-top: 0 }
            }
            @media (max-width: 767px) {
                #wrap > .container {
                    padding-top: 0;
                    padding-bottom: 20px;
                }
                #footer {
                    margin-left: -20px;
                    margin-right: -20px;
                    padding-left: 20px;
                    padding-right: 20px;
                }
            }
        </style>
        <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">
        <link href="{{ STATIC_URL }}css/style-responsive.css" rel="stylesheet">
    {% endblock style %}

	<link rel="index" title="boralanchar.com.br" href="http://www.boralanchar.com.br" />
	<link rel="canonical" href="http://www.boralanchar.com.br" /> 

	<meta http-equiv="refresh" content="3600" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="{{ STATIC_URL }}favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="{{ STATIC_URL }}favicon.ico" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{ STATIC_URL }}apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{ STATIC_URL }}apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{ STATIC_URL }}apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}apple-touch-icon-57-precomposed.png">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="{{ STATIC_URL }}js/html5shiv.js"></script>
    <![endif]-->

    <script src="{{ STATIC_URL }}js/jquery-1.7.2.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/boralanchar.js" type="text/javascript"></script>
    
    {% block head %}{% endblock %}

	<title>{% block title %}boralanchar.com.br :: Peça seu lanche!{% endblock %}</title>
</head>

<body>
{% block body %}
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                {% block header %}
                    {% include "header.html" %}
                {% endblock %}
            </div>
        </div>
    </header>

    <div id="wrap">
    <div class="container content">
        {% block content %}{% endblock %}
    </div>
    <div id="push"></div>
    </div>

    <div id="footer">
        <div class="container">
            {% include "footer.html" %}
            <p class="credit">&copy; 2013 - <a href="http://boralanchar.herokuapp.com">Boralanchar</a></p>
        </div>
    </div>
    
    {% block script %}{% endblock %}

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-30123307-1']);
        _gaq.push(['_setDomainName', 'boralanchar.com.br']);
        _gaq.push(['_trackPageview']);

        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
{% endblock body %}
</body>
</html>

boralanchar_heroku/templates/content.html
conteudo

boralanchar_heroku/templates/footer.html
<div class="row">
    <div class="span3">
        <nav class="footer_sobre_o_site">
            <h2>Sobre o site</h2>
            <ul>{% comment %}
                <li><a href="{% url website:como_acompanhar_meu_pedido %}">Acompanhar meu pedido</a></li>
                <li><a href="{% url website:como_funciona %}">Como faço para pedir?</a></li>
                <li><a href="{% url website:perguntas_frequentes %}">Perguntas frequentes</a></li>
                <li><a href="{% url website:termos_de_uso %}">Termos de uso/Política de privacidade</a></li>{% endcomment %}
                <li><a href="{% url 'website:contato' %}">Entre em contato conosco</a></li>
                <li><a href="{% url 'website:empresa' %}">A Empresa</a></li>
            </ul>
        </nav>
    </div>
    <div class="span4">
        <nav class="footer_estabelecimentos">
            <h2>Estabelecimentos</h2>
            <ul>
                <li><a href="{% url 'website:vantagens_estabelecimento' %}">Quais vantagens eu tenho como estabelecimento?</a></li>
                <li><a href="{% url 'website:indicar_estabelecimento' %}">Quero indicar um estabelecimento</a></li>
                {% comment %}<li><a href="{% url website:area_estabelecimento %}">Acesso à área de estabelecimentos</a></li>{% endcomment %}
            </ul>
        </nav>
    </div>
</div>

boralanchar_heroku/templates/header.html
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<a class="brand" href="{% url 'website:index' %}"><img src="{{ STATIC_URL }}img/logo-bl.png" alt="Boralanchar" title="Boralanchar"/></a>

<nav class="nav-collapse">
    {% comment %}<ul class="nav">
        <li class="active"><a href="{% url website:como_funciona %}">Como funciona</a></li>
        <li><a href="{% url website:meus_pedidos %}">Meus pedidos</a></li>
        <li><a href="{% url website:contato %}">Fale conosco</a></li>
    </ul>{% endcomment %}

    <ul class="nav pull-right">
        <li><a href="{% url 'website:contato' %}">Fale conosco</a></li>
        <li class="divider-vertical"></li>
        {% if user.is_authenticated %}
            <li>
                <div class="btn-group">
                    <button class="btn btn-danger"><a href="{% url 'user_dashboard' %}"><i class="icon-user icon-white"></i> {{ user }}</a></button>
                    <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></button>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'registration_update' user.pk %}"><i class="icon-edit"></i> Editar</a></li>
                        <li class="divider"></li>
                        <li><a href="{% url 'auth_password_change' %}"><i class="icon-refresh"></i> Alterar senha</a></li>
                    </ul>
                </div>
            </li>
            <li><a href="{% url 'auth_logout' %}">Sair</a></li>
        {% else %}
            <li><a href="{% url 'auth_login' %}"><i class="icon-user icon-white"></i>&nbsp;Entrar</a></li>
            <li><a href="{% url 'registration_register' %}">Cadastre-se</a></li>
        {% endif %}
    </ul>
</nav>

boralanchar_heroku/templates/user_dashboard.html
{% extends "base.html" %}
{% block title %}Perfil do usuário{% endblock %}
{% block style %}
    {{ block.super }}
    <style type="text/css">
    ul.my-user-profile {
        list-style: none;
        margin: 0;
    }
    </style>
{% endblock %}
{% block content %}
    <section>
        <div class="page-header">
            <h1>Conta de {{ user.get_full_name }} <small>configurações do usuário</small></h1>
        </div>
        <h2>Perfil</h2>
        <p>Configurações do perfil</p>
        <ul class="clearfix my-user-profile">
            <li>
                <i class="icon-edit"></i>
                <a href="{% url 'registration_update' user.pk %}">Editar</a>
            </li>
        </ul>

        {% if estabelecimentos %}
        <br/>
        <h2>Estabelecimentos</h2>
        <ul>
            {% for estabelecimento in estabelecimentos %}
            <li>
                <a href='{% url 'dashboard:pedidos' estabelecimento.id %}'>{{ estabelecimento }}</a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}

        <br/>
        <h2>Segurança</h2>
        <p>Configurações de segurança do usuário</p>
        <ul class="clearfix my-user-profile">
            <li>
                <i class="icon-refresh"></i>
                <a href="{% url 'auth_password_change' %}">Alterar senha</a>
            </li>
        </ul>
    </section>
{% endblock %}