boralanchar_heroku/urls.py
# coding: utf-8

from users.views import UserDashboardView
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^estabelecimento/', include('estabelecimento.urls', namespace='estabelecimento')),
                       url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
                       url(r'^location/', include('location.urls', namespace='location')),

                       # User dashboard
                       url(r'^user/dashboard/$', UserDashboardView.as_view(), name='user_dashboard'),

                       # Accounts
                       url(r'^accounts/', include('accounts.urls')),

                       # Cart
                       url(r'^cart/', include('cart.urls', namespace='cart')),

                       url(r'^', include('website.urls', namespace='website'))) + static(settings.MEDIA_URL,
                                                                                              document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('cart.views',
    url(r'^$', 'get_cart', name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'add_to_cart', name='add'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/new/$', 'add_to_cart',
        kwargs={'ensure_new': True}, name='add_new'),
    url(r'^decrement/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'decrement_quantity', name='decrement'),
    url(r'^decrement/item/(?P<item_id>\d+)/(?P<quantity>\d+)/$',
        'decrement_item_quantity', name='decrement_item'),
    url(r'^remove/(?P<product_id>\d+)/$', 'remove_from_cart', name='remove'),
)

dashboard/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, url

urlpatterns = patterns('dashboard.views',
    url(r'^(?P<id_estabelecimento>\d+)/toggle/$',
        'toggle_estabelecimento', name='toggle_estabelecimento'),

    url(r'^(?P<id_estabelecimento>\d+)/pedidos/$',
        'pedidos_view', name='pedidos'),

    url(r'^(?P<id_estabelecimento>\d+)/pedido/(?P<id_pedido>\d+)/$',
        'pedido_detail', name='pedido'),

    url(r'^(?P<id_estabelecimento>\d+)/pedido/(?P<id_pedido>\d+)/edit/status/$',
        'muda_status_pedido', name='muda_status_pedido'),

    url(r'^(?P<id_estabelecimento>\d+)/produtos/$',
        'produtos_view', name='produtos'),

    url(r'^(?P<id_estabelecimento>\d+)/produto/(?P<id_produto>\d+)/toggle/$',
        'produto_toggle_disponibilidade', name='produto_toggle_disponibilidade'),
)

location/urls.py
# coding: utf-8
from mixin import HybridDetailView
from models import Uf, Cidade, Bairro
from django.conf.urls import patterns, url
from views import GMapsTemplateView

urlpatterns = patterns('location.views',
    url(r'^set/', 'set', name='set'),
    url(r'^get/', 'get', name='get'),
    url(r'^clear/', 'clear', name='clear'),
    url(r'^cadastrar-endereco/$', GMapsTemplateView.as_view(), name='cadastrar-endereco'),
    
    (r'^uf/(?P<pk>\d)$', HybridDetailView.as_view(model=Uf)),
    (r'^cidade/(?P<pk>\d)$', HybridDetailView.as_view(model=Cidade)),
    (r'^bairro/(?P<pk>\d)$', HybridDetailView.as_view(model=Bairro)),
)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
# -*- coding:utf-8 -*-
from estabelecimento.models import Pedido, STATUS_PEDIDO_CHOICES
from django import forms

TEMPO_CHOICES = (
    (1, '1 dia'),
    (2, '2 dias'),
    (5, '5 dias'),
    (10, '10 dias'),
    (30, '30 dias')
)

class FiltroStatusPedidoForm(forms.Form):
    status = forms.MultipleChoiceField(label='Filtro de status', required=False,
        initial=[x[0] for x in STATUS_PEDIDO_CHOICES],
        choices=STATUS_PEDIDO_CHOICES, widget=forms.CheckboxSelectMultiple)
    tempo = forms.TypedChoiceField(label='Mostrar pedidos até', required=True, coerce=int, choices=TEMPO_CHOICES)


class MudaStatusPedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['status']

dashboard/views.py
# -*- coding:utf-8 -*-

from estabelecimento.models import Estabelecimento, Produto, STATUS_PEDIDO_CHOICES
from estabelecimento.models import STATUS_ESTABELECIMENTO_FECHADO, STATUS_ESTABELECIMENTO_ABERTO
from dashboard.forms import MudaStatusPedidoForm, FiltroStatusPedidoForm

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils import simplejson
from django.http import HttpResponse
from django.shortcuts import get_object_or_404 as get_object, render, redirect
from django.views.generic import TemplateView

from datetime import datetime, timedelta


class PedidosView(TemplateView):
    def get_context_data(self, **kwargs):
        context = super(PedidosView, self).get_context_data(**kwargs)
        request = self.request
        id_estabelecimento = kwargs['id_estabelecimento']
        estabelecimento = get_object(request.user.estabelecimentos, pk=id_estabelecimento)
        pedidos = estabelecimento.pedido_set.all()
        form = FiltroStatusPedidoForm(request.POST or request.GET or None)

        if form.is_bound and form.is_valid():
            filtro_tempo = form.cleaned_data['tempo']
            filtro_status = form.cleaned_data['status']

            timestamp = datetime.now() - timedelta(days=filtro_tempo)
            pedidos = pedidos.filter(data_hora__gt=timestamp)
            pedidos = pedidos.filter(status__in=filtro_status)

        # lista de listas (pedido, form)
        pedidos_plus_forms = [(pedido, MudaStatusPedidoForm(instance=pedido)) for pedido in pedidos]

        context['estabelecimento'] = estabelecimento
        context['form'] = form
        context['pedidos'] = pedidos_plus_forms
        return context

@login_required
def produtos_view(request, id_estabelecimento):
    estabelecimento = get_object(request.user.estabelecimentos, pk=id_estabelecimento)
    produto_set = estabelecimento.produto_set.all()
    return render(request, 'dashboard/produtos.html', {
        'estabelecimento': estabelecimento,
        'produtos': produto_set
    })


@login_required
def produto_toggle_disponibilidade(request, id_estabelecimento, id_produto):
    produto = get_object(Produto, pk=id_produto, estabelecimento=id_estabelecimento)

    produto.ativo = not produto.ativo
    produto.save()
    return redirect('dashboard:produtos', id_estabelecimento=id_estabelecimento)


@login_required
def pedidos_view(request, id_estabelecimento):
    estabelecimento = get_object(request.user.estabelecimentos, pk=id_estabelecimento)
    pedidos = estabelecimento.pedido_set.all()

    form = FiltroStatusPedidoForm(request.GET or None)

    if form.is_bound and form.is_valid():
        filtro_tempo = form.cleaned_data['tempo']
        filtro_status = form.cleaned_data['status']

        timestamp = datetime.now() - timedelta(days=filtro_tempo)
        pedidos = pedidos.filter(data_hora__gt=timestamp)
        pedidos = pedidos.filter(status__in=filtro_status)

    # lista de listas (pedido, form)
    pedidos = [(pedido, MudaStatusPedidoForm(instance=pedido)) for pedido in pedidos]

    return render(request, 'dashboard/pedidos.html', {
        'estabelecimento': estabelecimento,
        'pedidos': pedidos,
        'form_filtro':form,
        'lista_status_choices': STATUS_PEDIDO_CHOICES,
    })


@login_required
def muda_status_pedido(request, id_estabelecimento, id_pedido):
    estabelecimento = get_object(request.user.estabelecimentos, pk=id_estabelecimento)
    pedido = get_object(estabelecimento.pedido_set, pk=id_pedido)

    form = MudaStatusPedidoForm(request.POST or None, instance=pedido)
    status = 403

    if form.is_bound and form.is_valid():
        form.save()
        status = 200

    if request.is_ajax():
        response_data = simplejson.dumps({'id': "%06d" % pedido.id})
        return HttpResponse(response_data, status=status, mimetype='application/json')
    return redirect('dashboard_pedido', id_estabelecimento=id_estabelecimento, id_pedido=id_pedido)


@login_required
def pedido_detail(request, id_estabelecimento, id_pedido):
    estabelecimento = get_object(request.user.estabelecimentos, pk=id_estabelecimento)
    pedido = get_object(estabelecimento.pedido_set, pk=id_pedido)
    form = MudaStatusPedidoForm(request.POST or None, instance=pedido)
    act = request.GET.get('act')

    if form.is_bound:
        status = 403

        if form.is_valid():
            form.save()
            messages.info(request, message='Pedido %03d atualizado.' % estabelecimento.id)
            return redirect('dashboard_pedido', id_estabelecimento=id_estabelecimento, id_pedido=id_pedido)

    return render(request, 'dashboard/pedido.html', {
        'estabelecimento': estabelecimento,
        'pedido':pedido,
        'form': form,
        'act': act,
        'status_choices': STATUS_PEDIDO_CHOICES,
    })


def ajax_lista_pedidos(request, id_estabelecimento):
    if not request.user.is_authenticated():
        return HttpResponse('', status=404)

    estabelecimentos = request.user.estabelecimentos.all()
    estabelecimento = get_object(estabelecimentos, pk=id_estabelecimento)
    pedidos = estabelecimento.pedido_set.all()

    filters = request.GET.get('filters', None)

    if filters:
        st_list = [st for st in filters.split(',') if st.isdigit()]
        pedidos = pedidos.filter(status__in=st_list)

    return simplejson.dumps(pedidos)


@login_required
def toggle_estabelecimento(request, id_estabelecimento):
    """
    Muda o status do estabelecimento entre aberto e fechado
    """
    estabelecimentos = request.user.estabelecimentos.all()
    estabelecimento = get_object(estabelecimentos, pk=id_estabelecimento)

    if estabelecimento.status == STATUS_ESTABELECIMENTO_ABERTO:
        estabelecimento.status = STATUS_ESTABELECIMENTO_FECHADO
    else:
        estabelecimento.status = STATUS_ESTABELECIMENTO_ABERTO
    estabelecimento.save()
    return redirect('dashboard:pedidos', id_estabelecimento=id_estabelecimento)

dashboard/templates/dashboard/pedido.html
<html>

<head>
    {% block script %}
        <script type="text/javascript">
            var act = '{{ act }}';
            if (act == 'print'){
                window.print();
                window.close();
            }
        </script>
    {% endblock %}
</head>

<body>


{% block content %}
    <h3><a href="{% url 'dashboard:pedidos' estabelecimento.id %}">{{ estabelecimento }}</a></h3>
    <h4>Pedido {{ pedido }}</h4>

    {% if messages %}
        {% for msg in messages %}
            {{ msg }}
        {% endfor %}
    {% endif %}

    {% with pedido.cliente as cliente %}
    {% include "dashboard/includes/descricao_pedido.html" %}
    {% endwith %}
{% endblock %}
</body>
</html>

dashboard/templates/dashboard/pedidos.html
{% extends "base.html" %}

{% block style %}
    {{ block.super }}
    <style type="text/css">
        #form_filters ul *{ display:inline; }
        li.pedido{ cursor:default; }
    </style>
{% endblock %}

{% block head %}
    {{ block.super }}
    <meta http-equiv="refresh" CONTENT="60" />
{% endblock %}

{% block script %}
<script src="{{ STATIC_URL }}js/jquery-ui-1.9.2.custom.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.cookie.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/noty/jquery.noty.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/noty/layouts/top.js" type="text/javascript"></script>
<script src="{{ STATIC_URL }}js/noty/themes/default.js" type="text/javascript"></script>

<script type="text/javascript">
    var id_estabelecimento = {{ estabelecimento.id }};
    var url_muda_status_pedido = "/dashboard/{0}/pedido/{1}/edit/status/".replace('{0}', id_estabelecimento);

    $(document).ready(function(){
        $('.pedidos').accordion({
            collapsible: true,
            active: false,
            header: "span"
        });

        $('.pedidos select').change(function(e){
            var parent = $(this).parent();
            var id_parent = parent.attr('id');
            var id_pedido = id_parent.split('_')[1];
            var url = url_muda_status_pedido.replace('{1}', id_pedido);
            var value = $(this).val();

            $.ajax({
                url:url,
                dataType: 'json',
                type:"POST",
                data:{
                    status: value,
                    csrfmiddlewaretoken: $.cookie('csrftoken')
                },
                success: function(data, txtstatus, xhr){
                    var msg_ok = 'Pedido {1} atualizado.';
                    var msg_error = 'Não foi possível atualizar o pedido {1}.';
                    if(txtstatus == 'success')
                        noty({
                            text: msg_ok.replace('{1}', data['id']),
                            timeout: 2000,
                            type: 'success'
                        });
                    else
                        noty({
                            text: msg_error.replace('{1}', data[id]),
                            timeout: 2000,
                            type: 'error'
                        });
                }
            });
        });
    });
    {# $.ajax(build_url_lista_pedidos($('#form_filters').serialize())); #}
</script>
{% endblock %}

{% block content %}
    <h2>{{ estabelecimento }} - <span>{{ estabelecimento.funcionando|yesno:"Aberto,Fechado" }}</span></h2>
    <div>
        Horário de funcionamento: {{ estabelecimento.horario_funcionamento_hoje }} - <a href="{% url 'dashboard:toggle_estabelecimento' estabelecimento.id %}">Mudar status</a>
    </div>

    <h3>Pedidos - <a href="{% url 'dashboard:produtos' estabelecimento.id %}">Produtos</a></h3>
    <form id="form_filters" method="get" action="">{% csrf_token %}
        {{ form_filtro.as_p }}

        <input type="submit" value="Filtrar" />
    </form>

    <ul class='pedidos'>
        {% for pedido,form in pedidos %}
            <li class="pedido" id="pedido_{{ pedido.id }}">
                {{ form.status }}
                <a href="{% url 'dashboard:pedido' estabelecimento.id pedido.id %}?act=print" target="_blank">Imprimir</a>
                <span>{{ pedido }}</span>

                {% with pedido.cliente as cliente %}
                <div>
                    {% include "dashboard/includes/descricao_pedido.html" %}
                </div>
                {% endwith %}
            </li>
        {% empty %}
            {% if tempo_pedidos == 1 %}
                <li>Nenhum pedido efetuado na última hora.</li>
            {% else %}
                <li>Nenhum pedido efetuado nas últimas {{ tempo_pedidos }} horas.</li>
            {% endif %}
        {% endfor %}
    </ul>

{% endblock %}

dashboard/templates/dashboard/produtos.html
{% extends "base.html" %}

{% block content %}
    <h2>{{ estabelecimento }} - <span>{{ estabelecimento.funcionando|yesno:"Aberto,Fechado" }}</span></h2>
    <div>
        Horário de funcionamento: {{ estabelecimento.horario_funcionamento_hoje }} - <a href="{% url dashboard:toggle_estabelecimento estabelecimento.id %}">Mudar status</a>
    </div>

    <h3><a href="{% url 'dashboard:pedidos' estabelecimento.id %}">Pedidos</a> - Produtos</h3>
    {% if produtos.count %}
    <ul>
    {% for produto in produtos %}
        <li>{{ produto }} ({{ produto.ativo|yesno:"disponível,indisponível" }})
            <a href="{% url 'dashboard:produto_toggle_disponibilidade' produto.estabelecimento_id produto.id %}">({{ produto.ativo|yesno:"Tornar indisponível,Tornar disponível" }})</a></li>
    {% endfor %}
    </ul>
    {% endif %}
{% endblock %}