boralanchar_heroku/urls.py
# coding: utf-8

from users.views import UserDashboardView
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),

                       url(r'^estabelecimento/', include('estabelecimento.urls', namespace='estabelecimento')),
                       url(r'^dashboard/', include('dashboard.urls', namespace='dashboard')),
                       url(r'^location/', include('location.urls', namespace='location')),

                       # User dashboard
                       url(r'^user/dashboard/$', UserDashboardView.as_view(), name='user_dashboard'),

                       # Accounts
                       url(r'^accounts/', include('accounts.urls')),

                       # Cart
                       url(r'^cart/', include('cart.urls', namespace='cart')),

                       url(r'^', include('website.urls', namespace='website'))) + static(settings.MEDIA_URL,
                                                                                              document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

cart/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('cart.views',
    url(r'^$', 'get_cart', name='get'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'add_to_cart', name='add'),
    url(r'^add/(?P<product_id>\d+)/(?P<quantity>\d+)/new/$', 'add_to_cart',
        kwargs={'ensure_new': True}, name='add_new'),
    url(r'^decrement/(?P<product_id>\d+)/(?P<quantity>\d+)/$', 'decrement_quantity', name='decrement'),
    url(r'^decrement/item/(?P<item_id>\d+)/(?P<quantity>\d+)/$',
        'decrement_item_quantity', name='decrement_item'),
    url(r'^remove/(?P<product_id>\d+)/$', 'remove_from_cart', name='remove'),
)

location/urls.py
# coding: utf-8
from mixin import HybridDetailView
from models import Uf, Cidade, Bairro
from django.conf.urls import patterns, url
from views import GMapsTemplateView

urlpatterns = patterns('location.views',
    url(r'^set/', 'set', name='set'),
    url(r'^get/', 'get', name='get'),
    url(r'^clear/', 'clear', name='clear'),
    url(r'^cadastrar-endereco/$', GMapsTemplateView.as_view(), name='cadastrar-endereco'),
    
    (r'^uf/(?P<pk>\d)$', HybridDetailView.as_view(model=Uf)),
    (r'^cidade/(?P<pk>\d)$', HybridDetailView.as_view(model=Cidade)),
    (r'^bairro/(?P<pk>\d)$', HybridDetailView.as_view(model=Bairro)),
)

location/models.py
# coding=utf-8
from django.db import models


class Uf(models.Model):
    abreviatura = models.CharField(max_length=2)
    descricao = models.CharField(max_length=255, verbose_name='Descrição')

    class Meta:
        verbose_name = 'Uf'
        ordering = ['abreviatura']
        unique_together = ('abreviatura', 'descricao')

    @property
    def cidades(self):
        cidades = self.cidade_set.all()
        clist = []

        for cidade in cidades:
            clist.append(
                {'pk': cidade.pk, 'nome': cidade.descricao}
            )

        return clist

    def __unicode__(self):
        return self.abreviatura

    def as_dict(self):
        return {
            'pk': self.pk,
            'sigla': self.abreviatura,
            'cidades': list(self.cidades),
        }


class Cidade(models.Model):
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    uf = models.ForeignKey('Uf')

    class Meta:
        ordering = ['descricao']
        unique_together = ('descricao', 'uf')

    @property
    def bairros(self):
        bairros = self.bairro_set.all()
        blist = []

        for bairro in bairros:
            blist.append(
                {'pk': bairro.pk, 'nome': bairro.descricao}
            )

        return blist

    def __unicode__(self):
        return u'%s - %s' % (self.descricao, self.uf)

    def as_dict(self):
        return {
            'pk': self.pk,
            'nome': self.descricao,
            'uf_pk': self.uf.pk,
            'bairros': list(self.bairros),
        }


class Bairro(models.Model):
    descricao = models.CharField(max_length=255, verbose_name='Descrição')
    cidade = models.ForeignKey('Cidade')

    class Meta:
        ordering = ['descricao']
        unique_together = ('descricao', 'cidade')

    def __unicode__(self):
        return u'%s - %s' % (self.descricao, self.cidade)

    def as_dict(self):
        return {
            'pk': self.pk,
            'nome': self.descricao,
            'cidade_pk': self.cidade.pk,
        }

location/forms.py
# coding=utf-8
from models import Uf, Cidade, Bairro
from django import forms


class EnderecoForm(forms.Form):
    uf = forms.ModelChoiceField(
        label="",
        empty_label="-- Selecione --",
        queryset=Uf.objects.order_by('descricao'),
        widget=forms.Select(attrs={'id': 'uf', 'class': 'full-width'}),
    )

    cidade = forms.ChoiceField(
        label="",
        widget=forms.Select(attrs={'id': 'cidade', 'class': 'full-width'})
    )

    bairro = forms.ChoiceField(
        label="",
        widget=forms.Select(attrs={'id': 'bairro', 'class': 'full-width'})
    )


class Endereco(object):
    def __init__(self, uf=None, cidade=None, bairro=None):
        self.uf = uf
        self.cidade = cidade
        self.bairro = bairro

    def as_dict(self):
        uf_dict = {}
        cidade_dict = {}
        bairro_dict = {}

        if self.uf:
            uf_dict = self.uf.as_dict()

        if self.cidade:
            cidade_dict = self.cidade.as_dict()

        if self.bairro:
            bairro_dict = self.bairro.as_dict()

        return {
            'uf': uf_dict,
            'cidade': cidade_dict,
            'bairro': bairro_dict,
        }

    def get_form(self):
        form = EnderecoForm()

        form.fields['uf'].initial = self.uf.pk

        cidades = [(o.id, str(o)) for o in self.uf.cidade_set.all()]
        form.fields['cidade'].choices = cidades

        form.fields['cidade'].initial = self.cidade.pk

        bairros = [(o.id, str(o)) for o in self.cidade.bairro_set.all()]
        form.fields['bairro'].choices = bairros

        form.fields['bairro'].initial = self.bairro.pk

        return form

    def __unicode__(self):
        return 'uf: %s, cidade: %s, bairro: %s' % (self.uf, self.cidade, self.bairro)


def endereco_por_nome(uf, cidade, bairro):
    endereco = Endereco()

    try:
        endereco.uf = Uf.objects.get(abreviatura=uf)

        try:
            endereco.cidade = Cidade.objects.get(uf=endereco.uf, descricao=cidade)

            try:
                endereco.bairro = Bairro.objects.get(cidade=endereco.cidade, descricao=bairro)
            except:
                endereco.bairro = None
        except:
            endereco.cidade = None
            endereco.bairro = None
    except:
        endereco.uf = None
        endereco.cidade = None
        endereco.bairro = None

    return endereco


# Test Form Maps
class GMapsForm(forms.Form):
    sublocality = forms.CharField(
        label='Bairro',
        help_text='Propriedade "sublocality" da API do Google Maps.',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
    )
    locality = forms.CharField(
        label='Cidade',
        help_text='Propriedade "locality" da API do Google Maps.',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
    )
    administrative_area_level_1 = forms.CharField(
        label='UF',
        help_text='Propriedade "administrative_area_level_1" da API do Google Maps.',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
    )

    administrative_area_level_1_long_name = forms.CharField(
        label=u'UF Descrição',
        help_text='Propriedade "administrative_area_level_1" da API do Google Maps.',
        widget=forms.TextInput(attrs={'readonly': 'readonly'}),
    )

location/views.py
# coding=utf-8
from location import settings
from forms import Endereco, endereco_por_nome
from models import Bairro, Uf, Cidade
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
import json
from django.views.generic.edit import FormView
from forms import GMapsForm


def set(request, redirect_to=settings.LOCATION_SUCCESS_REDIRECT_TO):
    if ('uf' in request.POST) and ('cidade' in request.POST) and ('bairro' in request.POST):
        uf = request.POST['uf']
        cidade = request.POST['cidade']
        bairro = request.POST['bairro']
        
        if (int(uf) > 0) and (int(cidade) > 0) and (int(bairro) > 0):
            try:
                endereco = Endereco()
                
                endereco.uf = get_object_or_404(Uf, pk=uf)
                endereco.cidade = get_object_or_404(Cidade, pk=cidade)
                endereco.bairro = get_object_or_404(Bairro, pk=bairro)
    
                request.session['endereco'] = endereco
            except ValueError:
                return redirect(reverse(redirect_to))
        else:
            messages.add_message(request, messages.ERROR, message=u'Erro no preenchimento dos os campos')
    else:
        messages.add_message(request, messages.ERROR, message=u'Preencha todos os campos')

    return redirect(reverse(redirect_to))


def get(request, redirect_to=settings.LOCATION_SUCCESS_REDIRECT_TO):
    if not request.is_ajax():
        return HttpResponse('Não é possível acessar este recurso por este meio.', status=400)

    if not (('u' in request.GET) and ('c' in request.GET) and ('b' in request.GET)):
        return HttpResponse(json.dumps(Endereco.as_dict()), content_type='application/json')
        
    endereco = endereco_por_nome(request.GET['u'], request.GET['c'], request.GET['b'])

    return HttpResponse(json.dumps(endereco.as_dict()), content_type='application/json')


def clear(request):
    if 'endereco' in request.session:
        del request.session['endereco']

    return redirect(reverse(settings.LOCATION_SUCCESS_REDIRECT_TO))


class GMapsTemplateView(FormView):
    template_name = 'form_cadastrar_endereco.html'
    form_class = GMapsForm

    def get_success_url(self):
        return reverse('location:cadastrar-endereco')

    def form_valid(self, form):
        # Salvar a UF
        uf_descricao = form.cleaned_data['administrative_area_level_1_long_name']
        uf_abreviatura = form.cleaned_data['administrative_area_level_1']
        uf, uf_created = Uf.objects.get_or_create(abreviatura=uf_abreviatura, descricao=uf_descricao)

        if uf_created:
            messages.add_message(self.request, messages.SUCCESS, u'Estado cadastrado com sucesso.')
        else:
            messages.add_message(self.request, messages.WARNING, u'O estado informado já foi cadastrado.')

        # Salvar a cidade associada a UF
        cidade_descricao = form.cleaned_data['locality']
        cidade, cidade_created = Cidade.objects.get_or_create(descricao=cidade_descricao, uf=uf)

        if cidade_created:
            messages.add_message(self.request, messages.SUCCESS, u'Cidade cadastrada com sucesso.')
        else:
            messages.add_message(self.request, messages.WARNING, u'A cidade informada já foi cadastrada.')

        # Salvar o bairro associado a uma cidade
        bairro_descricao = form.cleaned_data['sublocality']
        bairro, bairro_created = Bairro.objects.get_or_create(descricao=bairro_descricao, cidade=cidade)

        if bairro_created:
            messages.add_message(self.request, messages.SUCCESS, u'Bairro cadastrado com sucesso.')
        else:
            messages.add_message(self.request, messages.WARNING, u'O bairro informado já foi cadastrado.')

        return redirect(reverse('location:cadastrar-endereco'))

location/templates/form_alterar_localidade.html
<form id="form_local" class="local_modo_edicao" action="{% url 'location:set' %}" method="post">{% csrf_token %}
    <ul class="nav nav-list" style="padding: 0">
        <li class="label_bair_uf_cid">
            <div class="alert alert-success" style="padding: 10px">
                <div id="area_ajax">
                    {{ endereco_form }}
                </div>
                
                <a href="#" class="confirmar-alterar-localidade"><span class="icon-ok"></span>Confirmar</a>
                
                {% if endereco %}
                    <a href="#" class="cancelar-alterar-localidade"><span class="icon-ban-circle"></span>Cancelar</a>
                {% endif %}
            </div>
        </li>
    </ul>
</form>

<script type="text/javascript">
(function($) {$(document).ready(function() {
    var $uf_ajax = $("#uf");
    var $cidade_ajax = $("#cidade");
    var $bairro_ajax = $("#bairro");

    // Adicionando na div #area_ajax
    $("#area_ajax").append($cidade_ajax);
    $("#area_ajax").append($bairro_ajax);

    // Carrega cidades
    $uf_ajax.on("change", function(){
        var id_uf = $(this).val();
        $cidade_ajax.html($option_vazio);
        $bairro_ajax.html($option_vazio);
        
        $.get("/location/uf/" + id_uf, function(data){
        	preenche('#cidade', data.cidades);
        });
    });

    // Carrega bairros
    $cidade_ajax.on("change", function(){
        var id_cidade = $(this).val();
        $.get("/location/cidade/" + id_cidade, function(data){
        	preenche('#bairro', data.bairros);
        });
    });

    if ($cidade_ajax.val() == "" && $bairro_ajax.val() ==  ""){
        $cidade_ajax.attr("disabled", "disabled");
        $bairro_ajax.attr("disabled", "disabled")
    }

    $bairro_ajax.keypress(function(event) {
        if (event.which == 13) {
            event.preventDefault();
            
            if ($uf_ajax.val() && $cidade_ajax.val() && $bairro_ajax.val()){
                $("#form_local").submit();
            } else {
                $uf_ajax.focus();
            }
        }
    });

    $(".confirmar-alterar-localidade").click(function(event){
        event.preventDefault();
        if ($uf_ajax.val() && $cidade_ajax.val() && $bairro_ajax.val()){
            $("#form_local").submit();
        } else {
            $uf_ajax.focus();
        }
    });

    $(".cancelar-alterar-localidade").click(function(event){
        event.preventDefault();
        $("#form_local_leitura").show();
        $("#form_local").hide();
    });
});})(jQuery);
</script>

location/templates/form_cadastrar_endereco.html
{% extends "admin/base_site.html" %}
{% load i18n admin_modify %}
{% block title %}{% trans "Cadastrar endereço" %}{{ block.super }}{% endblock %}
{% block extrahead %}
    {{ block.super }}
    {{ media }}
    {{ form.media }}
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/gmaps-autocomplete.js"></script>
{% endblock %}
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin/css/forms.css" />
{% endblock %}
{% block coltype %}
    {% if ordered_objects %}colMS{% else %}colM{% endif %}
{% endblock %}
{% block content %}
<div id="content-main">
    <h1>Adicionar endereço</h1>
    <p>Adicione através do google maps o endereço do estabelecimento.</p>

    {% if form.errors %}
        <p class="errornote">
            {% blocktrans count counter=form.errors|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktrans %}
        </p>
        {{ form.non_field_errors }}
    {% endif %}

    <div class="form-row field-search">
        <div>
            <label for="id_search" class="required">Busca</label>
            <input type="text" name="search" id="id_search" placeholder="Digite um local" autocomplete="off" size="80">
            <p class="help">
                Ex: Bom Futuro, Fortaleza - Ceará
            </p>
        </div>
    </div>

    <form action="" method="post">{% csrf_token %}
        <div>
            <div class="submit-row">
                <input type="submit" value="Salvar" class="default" name="_save">
            </div>

            <fieldset class="module aligned wide">
                {% for field in form %}
                    <div class="form-row{% if field.errors %} errors{% endif %} field-{{ field.name }}">
                        {% if field.errors %}{{ field.errors }}{% endif %}
                        <div>
                            <label for="{{ field.auto_id }}" {% if field.field.required %}class="required"{% endif %}>{{ field.label }}</label>
                            {{ field }}
                            {% if field.help_text %}
                                <p class="help">
                                    {{ field.help_text }}
                                </p>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </fieldset>
        </div>
    </form>
</div>
<script type="text/javascript">document.getElementById("id_search").focus();</script>
{% endblock %}

location/templates/form_local_leitura.html
{% load locationtag %}

{% if not request.session.endereco %}
	{% location %}
{% else %}
	<script type="text/javascript">
		(function($) {$(document).ready(function() {
             $(".local_modo_edicao").hide();
		});})(jQuery);
	</script>
{% endif %}

<div id="form_local_leitura" class="local_modo_leitura">
    <ul class="nav nav-list" style="padding: 0">
        <li class="label_bair_uf_cid">
            <div class="alert alert-success" align="center">
                <strong class="bairro">{{ endereco.bairro.descricao }}</strong><br />
                <strong class="cidade">{{ endereco.cidade.descricao }}</strong> <span>/</span>
                <strong class="uf">{{ endereco.uf }}</strong><br />
                <a href="#" class="alterar-localidade"><span class="icon-edit"></span>Alterar</a>
            </div>
        </li>
    </ul>
</div>

<script type="text/javascript">
(function($) {$(document).ready(function() {
    $(".alterar-localidade").click(function(event){
        event.preventDefault();
        $("#form_local_leitura").hide();
        $("#form_local").show();
        $("#bairro").focus();
    });
});})(jQuery);
</script>

location/templates/location_tag.html
{% if not endereco %}
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
	<script src="{{ STATIC_URL }}js/location.js" type="text/javascript"></script>
	<script type="text/javascript">
	(function($) {$(document).ready(function() {
		   if($.browser.msie){
			   $(".local_modo_leitura").hide();
			   
			   $(self.uf).focus();
			   return;
		   }
		
			var geolocation = new boralanchar.Geolocation("{% url 'location:get' %}");

			geolocation.loading = function (self){
				$(".local_modo_leitura").hide();

				$(self.uf).attr('disabled', 'disabled');

				$(self.cidade).attr('disabled', 'disabled');
				$(self.bairro).attr('disabled', 'disabled');

				window.setTimeout(function() {
					$(self.uf).removeAttr('disabled');
					$(self.cidade).removeAttr('disabled');
					$(self.bairro).removeAttr('disabled');}, 1500);
			}

			geolocation.success = function (self, data){
				$(self.uf).removeAttr('disabled');
				$(self.cidade).removeAttr('disabled');
				$(self.bairro).removeAttr('disabled');
				
				$(self.bairro).focus();
			};

			geolocation.fail = function (self, error){
				$(".label_bair_uf_cid .alert").removeClass("alert-success")
				  							  .addClass("alert-error");
				
				$(self.uf).removeAttr('disabled');
				$(self.cidade).removeAttr('disabled');
				$(self.bairro).removeAttr('disabled');

				$(self.uf).focus();
			};

			geolocation.noGeolocation = geolocation.fail;			
			
			geolocation.start();
	});})(jQuery);
	</script>
{% endif %}